# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=100)),
                ('acontent', models.TextField(null=True)),
                ('apub_datatime', models.DateTimeField(auto_now=True)),
                ('aread', models.IntegerField()),
                ('isDelete', models.BooleanField(default=True)),
            ],
        ),
    ]
